[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
ffi = true
evm_version = "paris"
viaIR = true
optimizer = true
optimizer_runs = 200
gas_limit = 25000000

[rpc_endpoints]
hedera = "${HEDERA_RPC_URL}"

[profile.default.fuzz]
runs = 10
max_test_rejects = 65536
